# ─────────────────────────────────────────────────────
# 🚀 Autostart Applications
# These commands run once when Hyprland starts

exec-once = waybar                     # Status bar
exec-once = hyprpaper                  # Wallpaper manager
exec-once = udiskie -t                 # Tray-based automounter for USB drives
exec-once = wl-paste --type text --watch cliphist store      # Track text clipboard history
exec-once = wl-paste --type image --watch cliphist store     # Track image clipboard history
exec-once = wlsunset -l -6.2 -L 106.8  # Adjusts screen warmth based on location (Jakarta)
