# ─────────────────────────────────────────
# GENERAL WINDOW BEHAVIOR
# ─────────────────────────────────────────

windowrule {
  name = suppress-maximize
  match:class = .*
  suppress_event = maximize
}

# ─────────────────────────────────────────
# WORKSPACE RULES
# ─────────────────────────────────────────

windowrule {
  name = firefox-workspace
  match:class = ^(firefox)$
  workspace = 1
}

windowrule {
  name = spotify-workspace
  match:class = ^(Spotify)$
  workspace = 4
}

windowrule {
  name = discord-workspace
  match:class = ^(discord)$
  workspace = 5
}

windowrule {
  name = kenchi-workspace
  match:class = ^(kenchi)$
  workspace = special:slot1
}

windowrule {
  name = beekeeper-workspace
  match:class = ^(beekeeper-studio)$
  workspace = special:slot2
}

# ─────────────────────────────────────────
# FLOATING AND CENTERED WINDOWS
# ─────────────────────────────────────────

windowrule {
  name = pavucontrol-float
  match:class = ^(org\.pulseaudio\.pavucontrol)$
  float = on
  center = on
}

windowrule {
  name = blueman-float
  match:class = ^(blueman-manager)$
  float = on
  center = on
}

windowrule {
  name = mpv-float
  match:class = ^(mpv)$
  float = on
  center = on
}

windowrule {
    name = tabfzf-float
    match:class = ^(firefox)$
    match:title = ^(Extension: (Tab Fuzzy Switcher) - [tabfzf] tabfzf-switcher — Original profile — Mozilla Firefox)$
    float = on
    center = on
}
